name: Auto Test HTML Form with Score

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test and Score
        run: |
          mkdir -p TestResults
          dotnet test --no-build --logger "trx;LogFileName=TestResults/test_results.trx" || true
          
          passed=$(grep -oP 'Passed:\K\d+' TestResults/test_results.trx | head -1)
          failed=$(grep -oP 'Failed:\K\d+' TestResults/test_results.trx | head -1)
          total=$(grep -oP 'Total:\K\d+' TestResults/test_results.trx | head -1)

          echo "✅ Score: $passed / $total tests passed"

          if [ "$failed" -gt 0 ]; then
            echo "❌ Some tests failed. Failing workflow."
            exit 1
          fi
